services:
  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: unless-stopped
    networks:
      - inception

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: unless-stopped
    ports:
      - "21:21"
      - "40000-40010:40000-40010"
    env_file:
      - .env
    volumes:
      - wordpress_data:/home/ftpuser
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aylaaouf/data/db_data
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aylaaouf/data/wordpress_data

networks:
  inception:
    driver: bridge
