services:
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - inception

  portainer:
    build: ./requirements/bonus/portainer
    image: portainer
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    secrets:
      - portainer_password.txt
    networks:
      - inception
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "6060:6060"
    networks:
        - inception
  resume:
    build: ./requirements/bonus/resume
    image: resume
    container_name: resume
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - inception
  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    restart: unless-stopped
    ports:
      - "21:21"
      - "40000-40010:40000-40010"
    env_file:
      - .env
    volumes:
      - wordpress_data:/home/ftpuser
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    image: nginx
    env_file:
      - .env
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aylaaouf/data/db_data
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aylaaouf/data/wordpress_data
  portainer_data:

networks:
  inception:
    driver: bridge

secrets:
  portainer_password.txt:
    file: ../secrets/portainer_password.txt